/**
 * @license MIT
 * @copyright (c) 2021 Julien Gonzalez <hello@spinjs.com>
 */

const Ajv = require('ajv');
const schema = require('./csl-json.schema.json');
const {constant, from_ris, to_ris } = require('./transform');

const ajv = new Ajv({allowUnionTypes: true, strictTypes: false});
ajv.addSchema(schema);
const validate = ajv.getSchema('https://resource.citationstyles.org/schema/v1.0/input/json/csl-data.json#/items');

const date = str => ({ raw: str });
const name = str => str; // TODO

// RIS -> CSL-JSON
module.exports.to = from_ris(validate,
  { __: 0
  , 'A2.ADVS':    ['performer[]'         , name]
  , 'A2.ANCIENT': ['editor[]'            , name]
  , 'A2.BILL':    ['organizer[]'         , name]
  , 'A2.BLOG':    ['editor[]'            , name]
  , 'A2.BOOK':    ['series-creator[]'    , name]
  , 'A2.CASE':    ['author[]'            , name]
  , 'A2.CHAP':    ['editor[]'            , name]
  , 'A2.CHART':   ['container-title'           ]
  , 'A2.CLSWK':   ['series-creator[]'    , name]
  , 'A2.COMP':    ['series-creator[]'    , name]
  , 'A2.CONF':    ['editor[]'            , name]
  , 'A2.CPAPER':  ['editor[]'            , name]
  , 'A2.CTLG':    ['producer[]'          , name]
  , 'A2.DATA':    ['producer[]'          , name]
  , 'A2.DATA':    ['series-creator[]'    , name]
  , 'A2.DICT':    ['editor[]'            , name]
  , 'A2.EBOOK':   ['editor[]'            , name]
  , 'A2.ECHAP':   ['editor[]'            , name]
  , 'A2.EDBOOK':  ['series-creator[]'    , name]
  , 'A2.ELEC':    ['series-creator[]'    , name]
  , 'A2.ENCYC':   ['editor[]'            , name]
  , 'A2.EQUA':    ['container-title'           ]
  , 'A2.FIGURE':  ['container-title'           ]
  , 'A2.GEN':     ['author[]'            , name]
  , 'A2.ICOMM':   ['recipient[]'         , name]
  , 'A2.LEGAL':   ['organizer[]'         , name]
  , 'A2.MAP':     ['series-creator[]'    , name]
  , 'A2.MPCT':    ['series-creator[]'    , name]
  , 'A2.MULTI':   ['series-creator[]'    , name]
  , 'A2.MUSIC':   ['editor[]'            , name]
  , 'A2.PAMP':    ['producer[]'          , name]
  , 'A2.PAT':     ['organizer[]'         , name]
  , 'A2.PCOMM':   ['recipient[]'         , name]
  , 'A2.RPRT':    ['series-creator[]'    , name]
  , 'A2.SER':     ['editor[]'            , name]
  , 'A2.SLIDE':   ['performer[]'         , name]
  , 'A2.SOUND':   ['performer[]'         , name]
  , 'A2.UNBILL':  ['organizer[]'         , name]
  , 'A2.UNPB':    ['series-creator[]'    , name]
  , 'A2.VIDEO':   ['performer[]'         , name]
  , 'A3.ADVS':    ['series-creator[]'    , name]
  , 'A3.BLOG':    ['illustrator[]'       , name]
  , 'A3.BOOK':    ['editor[]'            , name]
  , 'A3.CASE':    ['organizer[]'         , name]
  , 'A3.CHAP':    ['series-creator[]'    , name]
  , 'A3.CONF':    ['series-creator[]'    , name]
  , 'A3.EBOOK':   ['series-creator[]'    , name]
  , 'A3.GEN':     ['author[]'            , name]
  , 'A3.MPCT':    ['producer[]'          , name]
  , 'A3.MUSIC':   ['series-creator[]'    , name]
  , 'A3.RPRT':    ['publisher'                 ]
  , 'A3.SER':     ['series-creator[]'    , name]
  , 'A3.SLIDE':   ['series-creator[]'    , name]
  , 'A3.SOUND':   ['series-creator[]'    , name]
  , 'A3.THES':    ['editor[]'            , name]
  , 'A3.VIDEO':   ['series-creator[]'    , name]
  , 'A4.ANCIENT': ['translator[]'        , name]
  , 'A4.BOOK':    ['translator[]'        , name]
  , 'A4.CASE':    ['authority'                 ]
  , 'A4.CHAP':    ['translator[]'        , name]
  , 'A4.CLSWK':   ['translator[]'        , name]
  , 'A4.CONF':    ['executive-producer[]', name]
  , 'A4.CTLG':    ['translator[]'        , name]
  , 'A4.DATA':    ['executive-producer[]', name]
  , 'A4.DICT':    ['translator[]'        , name]
  , 'A4.EDBOOK':  ['translator[]'        , name]
  , 'A4.ENCYC':   ['translator[]'        , name]
  , 'A4.GEN':     ['author[]'            , name]
  , 'A4.GRANT':   ['translator[]'        , name]
  , 'A4.MPCT':    ['performer[]'         , name]
  , 'A4.MUSIC':   ['producer[]'          , name]
  , 'A4.PAMP':    ['translator[]'        , name]
  , 'A4.RPRT':    ['division'                  ]
  , 'A4.SER':     ['editorial-director[]', name]
  , 'AB':         [/***  N/A ***/              ]
  , 'AD':         [/***  N/A ***/              ]
  , 'AN':         ['call-number'               ]
  , 'AU':         ['author[]'            , name]
  , 'C1':         ['']
  , 'C2':         ['']
  , 'C3':         ['']
  , 'C4':         ['']
  , 'C5':         ['']
  , 'C6':         ['']
  , 'C7':         ['']
  , 'C8':         ['']
  , 'CA':         ['']
  , 'CN':         ['call-number'               ]
  , 'CT':         [/***  N/A ***/              ]
  , 'CY.DBASE':   ['publisher-place'           ]
  , 'CY.EBOOK':   ['publisher-place'           ]
  , 'CY.ECHAP':   ['publisher-place'           ]
  , 'CY.EJOUR':   ['publisher-place'           ]
  , 'CY.GEN':     ['publisher-place'           ]
  , 'CY.LEGAL':   ['publisher-place'           ]
  , 'CY.MGZN':    ['publisher-place'           ]
  , 'CY.MUSIC':   ['publisher-place'           ]
  , 'CY.STAND':   ['publisher-place'           ]
  , 'CY':         ['event-place'               ]
  , 'DA.AGGR':    ['accessed'            , date]
  , 'DA.CASE':    ['event-date'          , date]
  , 'DA.DBASE':   ['accessed'            , date]
  , 'DA.EBOOK':   ['accessed'            , date]
  , 'DA.ECHAP':   ['accessed'            , date]
  , 'DA.EJOUR':   ['accessed'            , date]
  , 'DA.MPCT':    ['available-date'      , date]
  , 'DA.MULTI':   ['accessed'            , date]
  , 'DA.STAT':    ['event-date'          , date]
  , 'DA':         ['issued'              , date]
  , 'DB':         ['source'                    ]
  , 'DO':         ['DOI'                       ]
  , 'DP':         ['producer'            , name]
  , 'ET':         ['edition'                   ]
  , 'IS':         ['issue'                     ]
  , 'J2':         ['title-short'               ]
  , 'KW':         ['keyword'                   ]
  , 'L1':         ['']
  , 'L4':         ['']
  , 'LA':         ['language']
  , 'LB':         ['']
  , 'M1':         ['']
  , 'M2':         ['']
  , 'M3':         ['']
  , 'N1':         ['']
  , 'NV':         ['']
  , 'OP':         ['']
  , 'PB':         ['']
  , 'PY':         ['']
  , 'RI':         ['']
  , 'RN':         ['']
  , 'RP':         ['']
  , 'SE':         ['']
  , 'SN':         ['']
  , 'SP':         ['']
  , 'ST':         ['title-short']
  , 'SV':         ['']
  , 'T2':         ['']
  , 'T3':         ['']
  , 'TA':         ['']
  , 'TI':         ['title']
  , 'TT':         ['']
  , 'TY.ADVS':    ['type', constant('motion_picture')         ]
  , 'TY.AGGR':    ['type', constant('dataset')                ]
  , 'TY.ART':     ['type', constant('graphic')                ]
  , 'TY.BILL':    ['type', constant('bill')                   ]
  , 'TY.BLOG':    ['type', constant('post-weblog')            ]
  , 'TY.BOOK':    ['type', constant('book')                   ]
  , 'TY.CASE':    ['type', constant('legal_case')             ]
  , 'TY.CHAP':    ['type', constant('chapter')                ]
  , 'TY.CHART':   ['type', constant('figure')                 ]
  , 'TY.CLSWK':   ['type', constant('classic')                ]
  , 'TY.COMP':    ['type', constant('book')                   ]
  , 'TY.CONF':    ['type', constant('document')               ]
  , 'TY.CPAPER':  ['type', constant('paper-conference')       ]
  , 'TY.DATA':    ['type', constant('dataset')                ]
  , 'TY.DBASE':   ['type', constant('dataset')                ]
  , 'TY.DICT':    ['type', constant('entry-dictionary')       ]
  , 'TY.EBOOK':   ['type', constant('book')                   ]
  , 'TY.ECHAP':   ['type', constant('chapter')                ]
  , 'TY.EDBOOK':  ['type', constant('book')                   ]
  , 'TY.EJOUR':   ['type', constant('article-journal')        ]
  , 'TY.ELEC':    ['type', constant('webpage')                ]
  , 'TY.ENCYC':   ['type', constant('entry-encyclopedia')     ]
  , 'TY.EQUA':    ['type', constant('figure')                 ]
  , 'TY.FIGURE':  ['type', constant('figure')                 ]
  , 'TY.HEAR':    ['type', constant('hearing')                ]
  , 'TY.ICOMM':   ['type', constant('personal_communication') ]
  , 'TY.JFULL':   ['type', constant('article-journal')        ]
  , 'TY.JOUR':    ['type', constant('article-journal')        ]
  , 'TY.LEGAL':   ['type', constant('legislation')            ]
  , 'TY.MANSCPT': ['type', constant('manuscript')             ]
  , 'TY.MAP':     ['type', constant('map')                    ]
  , 'TY.MGZN':    ['type', constant('article-magazine')       ]
  , 'TY.MPCT':    ['type', constant('motion_picture')         ]
  , 'TY.MULTI':   ['type', constant('motion_picture')         ]
  , 'TY.MUSIC':   ['type', constant('musical_score')          ]
  , 'TY.NEWS':    ['type', constant('article-newspaper')      ]
  , 'TY.PAMP':    ['type', constant('pamphlet')               ]
  , 'TY.PAT':     ['type', constant('patent')                 ]
  , 'TY.PCOMM':   ['type', constant('personal_communication') ]
  , 'TY.RPRT':    ['type', constant('report')                 ]
  , 'TY.SOUND':   ['type', constant('song')                   ]
  , 'TY.STAND':   ['type', constant('standard')               ]
  , 'TY.STAT':    ['type', constant('legislation')            ]
  , 'TY.THES':    ['type', constant('thesis')                 ]
  , 'TY.UNBILL':  ['type', constant('bill')                   ]
  , 'TY.VIDEO':   ['type', constant('motion_picture')         ]
  , 'TY':         ['type', constant('document')               ]
  , 'UR':         ['URL'                                      ]
  , 'VL':         ['volume'                                   ]
  , 'Y2':         ['accessed', date                           ]});

// CSL-JSON -> RIS
module.exports.from = to_ris(validate,
  {});
