site_name: '@customcommander/ris'
site_url: https://customcommander.github.io/ris/manual
repo_url: https://github.com/customcommander/ris
edit_uri: ""
docs_dir: pages
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.sections
    - navigation.expand
    - content.code.annotate
markdown_extensions:
  - def_list
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Getting Started:
    - About: index.md
    - 'Read & Write': intro.md
  - Transform:
    - Mendeley: mendeley.md
  - Further Resources:
    - Online Playground: https://customcommander.github.io/ris/uat
