name: release

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup
        run: docker run -e NPM_TOKEN -e GH_TOKEN -d -i --rm --name risbox -v $GITHUB_WORKSPACE:/workspaces/dev customcommander/webdev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Release
        run: >
          docker exec risbox yarn &&
          docker exec risbox yarn semantic-release --no-ci
      - name: Cleanup
        run: docker kill risbox
