name: Generate Site

on:
  push:
    branches:
      - main
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: >
          mkdir -p static_site/uat &&
          cp uat/index.html static_site/uat/ &&
          docker run --rm -v $GITHUB_WORKSPACE/doc/manual:/workspaces/manual -w /workspaces/manual squidfunk/mkdocs-material:8.0.3 mkdocs build &&
          mv doc/manual/site static_site/manual

      - name: Publish
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: static_site
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
